// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDInl6nkD3KlgQVw6z29_PTKUvkBTjR0jE',
    appId: '1:398684772077:web:3d1f8655ab1034918c9ee4',
    messagingSenderId: '398684772077',
    projectId: 'dsx-can',
    authDomain: 'dsx-can.firebaseapp.com',
    databaseURL: 'https://dsx-can-default-rtdb.firebaseio.com',
    storageBucket: 'dsx-can.firebasestorage.app',
    measurementId: 'G-2KFRQQHMRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDEbTJCJuEje6UiyiOsgvMInDhHaXkE8',
    appId: '1:398684772077:android:737d9f5431b4a5f88c9ee4',
    messagingSenderId: '398684772077',
    projectId: 'dsx-can',
    databaseURL: 'https://dsx-can-default-rtdb.firebaseio.com',
    storageBucket: 'dsx-can.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUrCP59Yiywgl5FCoIA7pS_ntho0wHil4',
    appId: '1:398684772077:ios:b3af420b074aebc68c9ee4',
    messagingSenderId: '398684772077',
    projectId: 'dsx-can',
    databaseURL: 'https://dsx-can-default-rtdb.firebaseio.com',
    storageBucket: 'dsx-can.firebasestorage.app',
    iosBundleId: 'com.example.gp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUrCP59Yiywgl5FCoIA7pS_ntho0wHil4',
    appId: '1:398684772077:ios:b3af420b074aebc68c9ee4',
    messagingSenderId: '398684772077',
    projectId: 'dsx-can',
    databaseURL: 'https://dsx-can-default-rtdb.firebaseio.com',
    storageBucket: 'dsx-can.firebasestorage.app',
    iosBundleId: 'com.example.gp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDInl6nkD3KlgQVw6z29_PTKUvkBTjR0jE',
    appId: '1:398684772077:web:9e8e611d82b15bc18c9ee4',
    messagingSenderId: '398684772077',
    projectId: 'dsx-can',
    authDomain: 'dsx-can.firebaseapp.com',
    databaseURL: 'https://dsx-can-default-rtdb.firebaseio.com',
    storageBucket: 'dsx-can.firebasestorage.app',
    measurementId: 'G-0H4CRDNPRL',
  );
}
